name: CI

on: [push, pull_request]

jobs:
  check-project:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: ContosoStockDb
        # Aguarda o banco
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=ContosoStockDb;Username=admin;Password=admin"